apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault
  namespace: ${namespace}
  labels:
    platform.example.com/managed: "true"
  annotations:
    azure.workload.identity/client-id: ${keyvault_client_id}
    azure.workload.identity/tenant-id: ${azure_tenant_id}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: keyvault
  namespace: ${namespace}
  labels:
    platform.example.com/managed: "true"
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${keyvault_url}
      serviceAccountRef:
        name: keyvault
