apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: php-redis
          # Placeholder, the real image + tag come from base/kustomization.yaml
          image: guestbook-frontend
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: ENVIRONMENT
              value: ${environment}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz.php
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 256Mi
