# Tenant instances (= namespaces) running in the development cluster.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../tenants/fi-marketing-guestbook/main
  - ../../../tenants/fi-marketing-guestbook/dev2
